# Generated by Django 4.2.5 on 2023-09-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='PVC', max_length=50)),
                ('purpose', models.CharField(choices=[('ELECTRICAL RED/ORANGE', 'ELECTRICAL RED/ORANGE'), ('POTABLE WATER - BLUE', 'POTABLE WATER - BLUE'), ('SANITARY ORANGE/BROWN', 'SANITARY ORANGE/BROWN')], max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('size_in', models.CharField(max_length=50)),
                ('size_mm', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
